name: pesagem_frangos
description: Calcular o Peso Médio a partir das balanças informadas

version: 1.0.1+2

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.9
  share_plus: ^13.3.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
